/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.walletapp;

public class rnbridgewallet {
  public static void init_library(String arg0, String url) {
    rnbridgewalletJNI.init_library(arg0, url);
  }

  public static String invoke_cpp_method(String method, String json_param) {
    return rnbridgewalletJNI.invoke_cpp_method(method, json_param);
  }

}
