/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.walletapp;

public class rnbridgewalletJNI {
  public final static native void init_library(String jarg1, String jarg2);
  public final static native String invoke_cpp_method(String jarg1, String jarg2);

  static {
    try {
        System.loadLibrary("rnbridgewallet");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library librnbridgewallet.so failed to load. \n" + e);
      System.exit(1);
    }
  }

}
